// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/alanwade2001/spa-customer-api/repositories"
	"github.com/alanwade2001/spa-customer-api/routers"
	"github.com/alanwade2001/spa-customer-api/services"
	"github.com/alanwade2001/spa-customer-api/types"
	"github.com/gin-gonic/gin"
)

// Injectors from wire.go:

func InitialiseServerAPI() types.ServerAPI {
	engine := gin.Default()
	repositoryAPI := repositories.NewMongoService()
	serviceAPI := services.NewService(repositoryAPI)
	customerAPI := routers.NewCustomerRouter(serviceAPI)
	customerSearchAPI := routers.NewCustomerSearchRouter(repositoryAPI)
	registerAPI := routers.NewRegisterService(engine, customerAPI, customerSearchAPI)
	configAPI := services.NewConfigService()
	serverAPI := NewServer(engine, registerAPI, configAPI)
	return serverAPI
}
